### PR TITLE
add example query to show changelog

### PR DESCRIPTION
**Pull request by kelle**
helpful when not sure which version of the database one is using.

### CODE REVIEW

**Comment by dr-rodriguez** [comment]
There are 3 reasons I think this is not a worthwhile addition:
- The current version of the database online has no entries in the changelog. Public db users will just get an error message.
- The changelog table is not tracked by version. Future releases of the database will have entries there that refer to data that is not public and thus not available to most users.
- The example queries are meant to be examples of what public db users can do. Very few people will want to look at a changelog and will be more interested in the science content of the database. I would rather they practice their SQL on tables other than changelog.

**Comment by kelle** [comment]
I would like the web version to have some indication of the last modified date.

**Comment by dr-rodriguez** [comment]
I can work to add some dynamic text similar to what we have in the main query page. If you look at the very bottom it says the astrodbkit version that's running. The number of brown dwarfs on the first sentence is also something that gets dynamically updated. I could add somewhere on the text an indicator that will show the latest date value from the changelog entry (or 2015 if empty).

**Comment by kelle** [comment]
I noticed the number of sources change! And yes, some dynamic text with a date would be awesome. Clearly not high priority

**Comment by dr-rodriguez** [comment]
Have a look at the new line at the very bottom of the main query page. It should now pick up the last row of the changelog table and display the date+time. Feel free to move it if you think there's a better place for that.

**Pull request closed without merging**
